/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.amimobenja.www;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author afro
 */
public class MaizeBagBought extends javax.swing.JFrame {
    public static java.sql.Connection connectDB = null;
    java.lang.String userName = null;
    com.amimobenja.www.DBObject dbObject;
    java.lang.String price;

    /**
     * Creates new form TinPrices1
     */
    public MaizeBagBought(java.sql.Connection connDb, java.lang.String username) {
        connectDB = connDb;
        userName = username;
        dbObject = new com.amimobenja.www.DBObject();
        
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        noBagBoughtLbl = new javax.swing.JLabel();
        noBagBoughtTxt = new javax.swing.JTextField();
        costPerBagLbl = new javax.swing.JLabel();
        costPerBagTxt = new javax.swing.JTextField();
        btnPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        totalCostTxt = new javax.swing.JTextField();
        totalCostLbl = new javax.swing.JLabel();
        estiTinsTxt = new javax.swing.JTextField();
        tinsPerBagTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Maize Bag Prices Set-up");
        setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Maize Bag Details"));
        mainPanel.setToolTipText("");
        mainPanel.setLayout(new java.awt.GridBagLayout());

        noBagBoughtLbl.setText("No. of Maize Bag Bought");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(noBagBoughtLbl, gridBagConstraints);

        noBagBoughtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBagBoughtTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(noBagBoughtTxt, gridBagConstraints);

        costPerBagLbl.setText("Cost per Bag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(costPerBagLbl, gridBagConstraints);

        costPerBagTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costPerBagTxtKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(costPerBagTxt, gridBagConstraints);

        btnPanel.setLayout(new java.awt.GridBagLayout());

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        btnPanel.add(saveBtn, gridBagConstraints);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        btnPanel.add(clearBtn, gridBagConstraints);

        cancelBtn.setText("Exit");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        btnPanel.add(cancelBtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(btnPanel, gridBagConstraints);

        totalCostTxt.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(totalCostTxt, gridBagConstraints);

        totalCostLbl.setText("Total Cost");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(totalCostLbl, gridBagConstraints);

        estiTinsTxt.setEditable(false);
        estiTinsTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estimated No. Of Tins", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        mainPanel.add(estiTinsTxt, gridBagConstraints);

        tinsPerBagTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tins Per Bag", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 0, 0)));
        tinsPerBagTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tinsPerBagTxtKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        mainPanel.add(tinsPerBagTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noBagBoughtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBagBoughtTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noBagBoughtTxtActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        java.util.Calendar cal = java.util.Calendar.getInstance();
        java.util.Date todayDate = cal.getTime();
        
        Double z = 0.00;
        
        String a = Double.toString(((Double.valueOf(noBagBoughtTxt.getText()))*(Double.valueOf(costPerBagTxt.getText()))));
        String rem_bags = "0";
        
        try {
            

                System.out.println("About to Get the Maize Bags");

                java.sql.PreparedStatement pstm = connectDB.prepareStatement("SELECT SUM(rem_bags) FROM maize_bags_tbl");
                java.sql.ResultSet rse = pstm.executeQuery();

                System.out.println("To Get the Maize Bags");

                while (rse.next()) {
                    System.out.println("Getting the Maize Bags");
                    rem_bags = dbObject.getDBObject(rse.getObject(1), "0");

                }
                System.out.println("Remaining Bags - "+rem_bags);
                
                if (rem_bags.equals("0")) {
                    z = Double.valueOf(noBagBoughtTxt.getText());   
                    
                        if (!(noBagBoughtTxt.getText().equals("")) && (noBagBoughtTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$")) && 
                            !(costPerBagTxt.getText().equals("")) && (costPerBagTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$")) && 
                            !(totalCostTxt.getText().equals("")) && (a.matches("^[0-9]+(\\.[0-9]{1,4})?$")) && 
                            !(estiTinsTxt.getText().equals("")) && (estiTinsTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                        System.out.print("About to insert the values.!!!");

                        try {
                                connectDB.setAutoCommit(false);

                                java.sql.PreparedStatement pstmt = connectDB.prepareStatement("INSERT INTO maize_bags_tbl"
                                        + "(date, no_mbg_bght, cost_per_bag, total_cost, est_tins, rem_bags, user_name) VALUES (?, ?, ?, ?, ?, ?, ?)");

                                    pstmt.setDate(1, com.amimobenja.www.SQLDateFormat.getSQLDate(todayDate));
                                    pstmt.setDouble(2, Double.valueOf(noBagBoughtTxt.getText()));
                                    pstmt.setDouble(3, Double.valueOf(costPerBagTxt.getText()));
                                    pstmt.setDouble(4, Double.valueOf(a));
                                    pstmt.setDouble(5, Double.valueOf(estiTinsTxt.getText()));
                                    pstmt.setDouble(6, z);
                                    pstmt.setString(7, userName);

                                    pstmt.executeUpdate();
                                    connectDB.commit();
                                    connectDB.setAutoCommit(true);

                                    System.out.print("\nSuccess!!! Maize Bag Details saved successfully");
                                    JOptionPane.showMessageDialog(null, "The Maize Bag Details have been saved successfully. ", 
                                        "Success!!! Maize Bag Details saved successfully", JOptionPane.INFORMATION_MESSAGE);

                                    clear();


                            } catch (java.lang.Exception sq) {

                                try {
                                    connectDB.rollback();
                                } catch (java.sql.SQLException sql) {
                                    javax.swing.JOptionPane.showMessageDialog(this, sql.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
                                }
                                System.out.println(sq.getMessage());
                                javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                    } else {            
                        if (noBagBoughtTxt.getText().equals("")) {
                            noBagBoughtLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field No. of Maize Bag Bought is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (costPerBagTxt.getText().equals("")) {
                            costPerBagLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Cost per Bag is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (totalCostTxt.getText().equals("")) {
                            totalCostLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Total Cost is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (estiTinsTxt.getText().equals("")) {
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Estimated No. Of Tins is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        }  else if (!(noBagBoughtTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            noBagBoughtLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field No. of Maize Bag Bought has some unrecognized Values - "+noBagBoughtTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (!(costPerBagTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            costPerBagLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Cost per Bag has some unrecognized Values - "+costPerBagTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (!(totalCostTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            totalCostLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Total Cost has some unrecognized Values - "+totalCostTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (!(estiTinsTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Estimated No. Of Tins has some unrecognized Values - "+estiTinsTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        }

                    }
                    
                } else {
                    z = Double.valueOf(rem_bags) + Double.valueOf(noBagBoughtTxt.getText());
                    
                    if (!(noBagBoughtTxt.getText().equals("")) && (noBagBoughtTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$")) && 
                            !(costPerBagTxt.getText().equals("")) && (costPerBagTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$")) && 
                            !(totalCostTxt.getText().equals("")) && (a.matches("^[0-9]+(\\.[0-9]{1,4})?$")) && 
                            !(estiTinsTxt.getText().equals("")) && (estiTinsTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                        System.out.print("About to insert the values.!!!");

                        try {
                                connectDB.setAutoCommit(false);

                                java.sql.PreparedStatement pstmt = connectDB.prepareStatement("UPDATE maize_bags_tbl "
                                        + "SET date='"+com.amimobenja.www.SQLDateFormat.getSQLDate(todayDate)+"', no_mbg_bght='"+Double.valueOf(noBagBoughtTxt.getText())+"', "
                                        + "cost_per_bag='"+Double.valueOf(costPerBagTxt.getText())+"', total_cost='"+Double.valueOf(a)+"', "
                                        + "est_tins='"+Double.valueOf(estiTinsTxt.getText())+"', rem_bags='"+z+"', user_name='"+userName+"'");                                    

                                    pstmt.executeUpdate();
                                    connectDB.commit();
                                    connectDB.setAutoCommit(true);

                                    System.out.print("\nSuccess!!! Maize Bag Details saved successfully");
                                    JOptionPane.showMessageDialog(null, "The Maize Bag Details have been saved successfully. ", 
                                        "Success!!! Maize Bag Details saved successfully", JOptionPane.INFORMATION_MESSAGE);

                                    clear();


                            } catch (java.lang.Exception sq) {

                                try {
                                    connectDB.rollback();
                                } catch (java.sql.SQLException sql) {
                                    javax.swing.JOptionPane.showMessageDialog(this, sql.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
                                }
                                System.out.println(sq.getMessage());
                                javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                    } else {            
                        if (noBagBoughtTxt.getText().equals("")) {
                            noBagBoughtLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field No. of Maize Bag Bought is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (costPerBagTxt.getText().equals("")) {
                            costPerBagLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Cost per Bag is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (totalCostTxt.getText().equals("")) {
                            totalCostLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Total Cost is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (estiTinsTxt.getText().equals("")) {
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Estimated No. Of Tins is Empty.", "Empty Fields Noted! ", JOptionPane.ERROR_MESSAGE);
                        }  else if (!(noBagBoughtTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            noBagBoughtLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field No. of Maize Bag Bought has some unrecognized Values - "+noBagBoughtTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (!(costPerBagTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            costPerBagLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Cost per Bag has some unrecognized Values - "+costPerBagTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (!(totalCostTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            totalCostLbl.setForeground(Color.red);
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Total Cost has some unrecognized Values - "+totalCostTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        } else if (!(estiTinsTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$"))) {
                            JOptionPane.showMessageDialog(rootPane, "The Text Field Estimated No. Of Tins has some unrecognized Values - "+estiTinsTxt.getText(), 
                                    "Unrecognized Values Noted! ", JOptionPane.ERROR_MESSAGE);
                        }

                    }
                    
                    
                }
                
                
                
                System.out.println("Remaining Bags after if - "+rem_bags);
                System.out.println("Z - "+z);
                System.out.println("The Maize Tins should be set!");

            } catch (SQLException es) {
                System.out.println(es);

            }
        
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void costPerBagTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costPerBagTxtKeyReleased
        
        if (noBagBoughtTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$") && costPerBagTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$")) {
            String a = Double.toString(((Double.valueOf(noBagBoughtTxt.getText()))*(Double.valueOf(costPerBagTxt.getText()))));
            totalCostTxt.setText(new com.amimobenja.www.Format2Currency().Format2Currency(a));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Double check the Details Entered at No. of Maize Bag Bought - "+noBagBoughtTxt.getText()+" "
                    + "and Cost per Bag - "+costPerBagTxt.getText()+"! \n\nRemove any Spaces.", "Error! In Values.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_costPerBagTxtKeyReleased

    private void tinsPerBagTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinsPerBagTxtKeyReleased
        if (noBagBoughtTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$") && tinsPerBagTxt.getText().matches("^[0-9]+(\\.[0-9]{1,4})?$")) {
            estiTinsTxt.setText(Double.toString(Double.valueOf(noBagBoughtTxt.getText())*Double.valueOf(tinsPerBagTxt.getText())));        
        } else {
            JOptionPane.showMessageDialog(rootPane, "Unrecognized Values noted!", "Unknown Value!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tinsPerBagTxtKeyReleased
    
    public void clear() {
        noBagBoughtTxt.setText("");
        tinsPerBagTxt.setText("");
        estiTinsTxt.setText("");        
        costPerBagTxt.setText("");
        totalCostTxt.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel costPerBagLbl;
    private javax.swing.JTextField costPerBagTxt;
    private javax.swing.JTextField estiTinsTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel noBagBoughtLbl;
    private javax.swing.JTextField noBagBoughtTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tinsPerBagTxt;
    private javax.swing.JLabel totalCostLbl;
    private javax.swing.JTextField totalCostTxt;
    // End of variables declaration//GEN-END:variables
}
